# Generated by Django 4.2.24 on 2025-09-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_siteconfig'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cachedquote',
            name='unique_cached_symbol',
        ),
        migrations.RenameIndex(
            model_name='cachedquote',
            new_name='market_cach_symbol_3acbf5_idx',
            old_name='market_cach_symbol_1c5d40_idx',
        ),
    ]
