# Generated by Django 4.2.24 on 2025-09-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_cachedquote_unique_cached_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
