version: '3.9'
services:
  web:
    image: your-registry/your-namespace/stocks-heatmap:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=heatmap.settings
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - ALLOWED_HOSTS=*
      - GUNICORN_WORKERS=3
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=Zx56400772
    volumes:
      - heatmap_static:/app/staticfiles
      # Note: SQLite lives at /app/db.sqlite3 by default; to persist it, 
      # switch to Postgres (see postgres stack) or adjust settings to use /app/db/db.sqlite3 and mount that dir.
    restart: unless-stopped

volumes:
  heatmap_static:
