version: '3.9'
services:
  db:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_DB=heatmap
      - POSTGRES_USER=heatmap
      - POSTGRES_PASSWORD=heatmap
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: your-registry/your-namespace/stocks-heatmap:latest
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=heatmap.settings
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - ALLOWED_HOSTS=*
      - GUNICORN_WORKERS=3
      - DB_WAIT_TIMEOUT=60
      - DATABASE_URL=postgres://heatmap:heatmap@db:5432/heatmap
      # Set to your public HTTPS origins, comma-separated (required when using SSL)
      # Example: https://heatmap.example.com,https://www.example.com
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=Zx56400772
    volumes:
      - heatmap_static:/app/staticfiles
    restart: unless-stopped

volumes:
  pgdata:
  heatmap_static:
